import { Action, IResourceItem } from "@refinedev/core"

export const TitleHandler: (options: {
  resource?: IResourceItem
  action?: Action
  params?: Record<string, string | undefined>
  pathname?: string
  autoGeneratedTitle: string
}) => string = (options) => {
  let title = "Health-Care" // Default title
  if (options.resource && options.action) {
    title = `${options.resource} ${options.action} ${options.params?.id} | Health-Care`
  }
  return title
}